[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "pillow>=11.3.0",
    "psutil>=7.0.0",
    "pymupdf>=1.26.3",
    "reportlab>=4.4.3",
    "werkzeug>=3.1.3",
]
